import { User, Person, Organization, Time, PipelineStages } from "../../base";

export type DealDetailResponse = {
  id: number;
  creator_user_id: User;
  user_id: User;
  person_id: Person;
  org_id: Organization;
  stage_id: number;
  title: string;
  value: number;
  currency: string;
  add_time: string;
  update_time: string;
  stage_change_time: string;
  active: boolean;
  deleted: boolean;
  status: string;
  probability: null | number;
  next_activity_date: string;
  next_activity_time: string;
  next_activity_id: number;
  last_activity_id: null | number;
  last_activity_date: null | string;
  lost_reason: null | string;
  visible_to: string;
  close_time: null | string;
  pipeline_id: number;
  won_time: string;
  first_won_time: string;
  lost_time: string;
  products_count: number;
  files_count: number;
  notes_count: number;
  followers_count: number;
  email_messages_count: number;
  activities_count: number;
  done_activities_count: number;
  undone_activities_count: number;
  participants_count: number;
  expected_close_date: string;
  last_incoming_mail_time: string;
  last_outgoing_mail_time: string;
  label: string;
  stage_order_nr: number;
  person_name: string;
  org_name: string;
  next_activity_subject: string;
  next_activity_type: string;
  next_activity_duration: string;
  next_activity_note: string;
  formatted_value: string;
  weighted_value: number;
  formatted_weighted_value: string;
  weighted_value_currency: string;
  rotten_time: null | string;
  owner_name: string;
  cc_email: string;
  org_hidden: boolean;
  person_hidden: boolean;
  average_time_to_won: Time;
  average_stage_progress: number;
  age: Time;
  stay_in_pipeline_stages: PipelineStages;
  last_activity: null | string;
  next_activity: null | string;
};
